version: 2.1

orbs:
  python: circleci/python@1.5.0
  docker: circleci/docker@2.0.2

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Check Code Style
          command: flake8
  build-docker:
    environment:
      IMAGE_NAME: oc-lettings-site
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t "$DOCKER_HUB_USERNAME"/oc_lettings_site:"$CIRCLE_SHA1" .
      - run:
          name: Push to Docker Hub
          command: |
            docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_TOKEN"
            docker push "$DOCKER_HUB_USERNAME"/oc_lettings_site:"$CIRCLE_SHA1"
workflows:
  sample: 
    jobs:
      - build-and-test
      - build-and-push-docker:
        requires:
          - build-and-test
        filters:
            branches:
              only: master






  deploy:
    machine: true
    steps:
      - checkout
      - run:
         name: Build app and send Docker IMG to Heroku
         command: |
          sudo curl https://cli-assets.heroku.com/install.sh | sh
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a oclettings-matspyder web
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oclettings-matspyder web

workflows:
  sample: 
    jobs:
      - build-and-test
      - build-docker:
         requires:
           - build-and-test
         filters:
            branches:
               only: master
      - deploy:
         requires:
           - build-and-test
           - build-docker
         filters:
           branches:
             only: master

            